/*
   DGP - Deterministically Generated Passwords
   Filename: mainwindow.h
   Description: QT mainwindow header, this is pretty
                much is generated by QT.

   Author: Adam Oldham (ekcdd@gmx.com)

   Copyright (c) 2020  Adam Oldham
   All rights reserved.

   Distributed under the MIT/X11 software license, see the accompanying
   file license.txt or http://www.opensource.org/licenses/mit-license.php.

*/

#ifndef MAINWINDOW_H
#define MAINWINDOW_H

#include <QMainWindow>

#include "dgp.h"


QT_BEGIN_NAMESPACE
namespace Ui { class MainWindow; }
QT_END_NAMESPACE

class MainWindow : public QMainWindow
{
    Q_OBJECT

public:
    MainWindow(QWidget *parent = nullptr);
    ~MainWindow();

private:
    Ui::MainWindow *ui;
    DGPOptions options;


private slots:
   void handleButton();
   void handleGenerate();
   void CloseMe();
   void textCheck();
};
#endif // MAINWINDOW_H
